# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xQx1 <- function(Q, x) {
    .Call('_badlm_xQx1', PACKAGE = 'badlm', Q, x)
}

